version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./var/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
